apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-workshop-certificate
  namespace: default
spec:
  secretName: default-workshop-example-tls
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
  commonName: k8s-demo.win
  dnsNames:
  - k8s-demo.win
  - '*.k8s-demo.win'

