apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: nsoaiE_r9rrxe3mrbaLCc8iqKkgdo2DNElWH03ON
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-dns
spec:
  acme:
    email: holger.schneider@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: holger.schneider@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
